### PR TITLE
Update README.md to include updated environment variables

### PR DESCRIPTION
**Pull request by FearTheBadger**
Added the newly available environment variables used to change the data staleness to the README.

Signed-off-by: Brock Renninger <brock@renninger.dev>

### CODE REVIEW

**Review by spiffcs — APPROVED** [review]

**Comment by spiffcs** [comment]
Thanks @FearTheBadger! Can you sign the commit and we'll be set to merge?

**Comment by FearTheBadger** [comment]
I think the commit has been signed the way you'd like. Let me know if you would like me to do something different.

**Comment by spiffcs** [comment]
Apologies! The sign off is for the DCO check:
https://probot.github.io/apps/dco/

**Comment by FearTheBadger** [comment]
There we go, I think I signed it correctly now. Sorry about that.

**Pull request merged**
