### PR TITLE
add Gentoo matching support

### PR DESCRIPTION
**Pull request by zmedico**
Depends on https://github.com/anchore/syft/pull/1076

Closes: https://github.com/anchore/grype/issues/744

Signed-off-by: Zac Medico <zachary.medico@sony.com>

Here is a sample program that I have used to import Gentoo GLSA metadata into a grype database:

https://github.com/zmedico/grype-glsa-import/blob/main/main.go

### CODE REVIEW

**Comment by spiffcs** [comment]
This one is blocked on https://github.com/anchore/syft/pull/1076 being merged. I'll start cleaning it up and taking a look after that one gets a final review.

**Comment by spiffcs** [comment]
Feature for syft has been merged - In the process of cleaning this one up for merge now

**Comment by spiffcs** [comment]
Just working through integration tests now - thanks again @zmedico for the contribution here!

**Comment by spiffcs** [comment]
@zmedico I'm having a little trouble finding the file that identifies the distro in the `gentoo/portage` image. 

Do you have any recommendations on a file that might be packaged with the image akin to an `/etc/os-release` file?

Thanks!

**Comment by zmedico** [comment]
> @zmedico I'm having a little trouble finding the file that identifies the distro in the `gentoo/portage` image.
> 
> Do you have any recommendations on a file that might be packaged with the image akin to an `/etc/os-release` file?
 
The `gentoo/stage3` images should contain a proper `/etc/os-release` file:

https://hub.docker.com/r/gentoo/stage3

**Comment by spiffcs** [comment]
Thanks for the image tag!

If people were to use the `gentoo/portage` tag do you have any recommendations for detecting the distro on that path?

**Comment by zmedico** [comment]
> If people were to use the `gentoo/portage` tag do you have any recommendations for detecting the distro on that path?

The `gentoo/portage` tag is a package repository, not a distro. So, it doesn't make sense to try and detect a distro with this tag.

**Review by spiffcs — APPROVED** [review]
Approved - looking for a second member of @anchore/tools

**Comment by zmedico** [comment]
@spiffcs Thank you very much for you work on this and https://github.com/anchore/syft/pull/1076!

**Pull request merged**
