### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by luhring**
Updates github.com/containerd/containerd and github.com/ulikunitz/xz to resolve reported vulnerabilities

### CODE REVIEW

**Comment by luhring** [comment]
😱 

Will need to look into this...

```
...
go mod download
verifying github.com/anchore/syft@v0.28.0: checksum mismatch
	downloaded: h1:aYCaGazijOVcEFWAHKGks2N6dzSk4A7J+y2+pvd9uKI=
	go.sum:     h1:Ub/xWZsHrlNU9EI9U2dKxl2xdc92WnjBNc90rZgTBOA=

SECURITY ERROR
This download does NOT match an earlier download recorded in go.sum.
The bits may have been replaced on the origin server, or an attacker may
have intercepted the download attempt.

For more information, see 'go help module-auth'.
```

**Comment by spiffcs** [comment]
> 😱
> 
> Will need to look into this...
> 
> ```
> ...
> go mod download
> verifying github.com/anchore/syft@v0.28.0: checksum mismatch
> 	downloaded: h1:aYCaGazijOVcEFWAHKGks2N6dzSk4A7J+y2+pvd9uKI=
> 	go.sum:     h1:Ub/xWZsHrlNU9EI9U2dKxl2xdc92WnjBNc90rZgTBOA=
> 
> SECURITY ERROR
> This download does NOT match an earlier download recorded in go.sum.
> The bits may have been replaced on the origin server, or an attacker may
> have intercepted the download attempt.
> 
> For more information, see 'go help module-auth'.
> ```

This was also a case where we re tagged the release

**Comment by spiffcs** [comment]
@luhring This PR is out of date. I'm not sure if we still need to do this since other PR might have already run us forward re these dependencies.

**Comment by luhring** [comment]
@spiffcs 

>This PR is out of date. I'm not sure if we still need to do this since other PR might have already run us forward re these dependencies.

Yeah good point. I'll check it out and either rebase or close out this PR.

**Comment by luhring** [comment]
Rebased and dropped the Syft bump commit.

**Review by spiffcs — APPROVED** [review]

**Pull request merged**
