### PR TITLE
template: Check sanity for template file

### PR DESCRIPTION
**Pull request by Akasurde**
* Check if template file exists
* Check if template file is readable
* Check if template file is parsable using text\template

Signed-off-by: Abhijeet Kasurde <akasurde@redhat.com>

### CODE REVIEW

**Review by wagoodman — APPROVED** [review]
nice improvement 👍

**Comment by spiffcs** [comment]
I'll find some time to update the tests here so this can pass and we can merge it in

**Comment by luhring** [comment]
I believe this fixes #623 and #625

**Comment by spiffcs** [comment]
updated template tests asserting on new correct template - using the current template that was there through the error `no function toJson`

**Review by spiffcs — APPROVED** [review]
Approved now tests are passing

**Comment by Akasurde** [comment]
@spiffcs @wagoodman Thanks for the review and merge.

**Pull request merged**
