### PR TITLE
Added Docker example to Readme

### PR DESCRIPTION
**Pull request by AErmie**
Added an example of running grype using the Docker container method

### CODE REVIEW

**Comment by adriens** [comment]
cf https://github.com/anchore/grype/issues/732

**Comment by adriens** [comment]
Hi guys, all that is great. Any idea on how to achieve the same thing from `podman` ?

**Comment by spiffcs** [comment]
👋 Hi @AErmie! I just need you to check the DCO status of your commits:
https://github.com/anchore/grype/pull/769/checks?check_run_id=6692483308

Looks like they need to be signed. Follow the directions in the workflow above and I can then get this merged!

**Comment by AErmie** [comment]
Sorry for the double commit @spiffcs, I wasn't sure how to complete the signoff since I submitted the PR via the web browser. Thanks for that guidance. I also had to re-submit the signoff, since it didn't use my info the first time ;-). Hopefully this meets all the criteria now.

**Comment by spiffcs** [comment]
Thanks for the updates @AErmie!

**Review by spiffcs — APPROVED** [review]

**Pull request merged**
